on:
  workflow_dispatch
#  schedule:
#    - cron:  '30 23 * * *'

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release new eibi sqlite version

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.13.0'
      - run: mix deps.get
      - run: mix compile
      - run: echo "::set-output name=create_version::$(mix task create_version)"
        id: create_version
#      - run: echo "${{fromJson(steps.create_version.outputs.create_version).updated}}"
      - run: echo "${{steps.create_version.outputs.create_version}}"
